# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answeredit.ui'
#
# Created: Wed Aug 18 03:16:09 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AnswerEditWidget(object):
    def setupUi(self, AnswerEditWidget):
        AnswerEditWidget.setObjectName("AnswerEditWidget")
        AnswerEditWidget.resize(565, 214)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(AnswerEditWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.varsetList = QtGui.QListView(AnswerEditWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varsetList.sizePolicy().hasHeightForWidth())
        self.varsetList.setSizePolicy(sizePolicy)
        self.varsetList.setMinimumSize(QtCore.QSize(128, 0))
        self.varsetList.setMaximumSize(QtCore.QSize(128, 16777215))
        self.varsetList.setAlternatingRowColors(True)
        self.varsetList.setMovement(QtGui.QListView.Snap)
        self.varsetList.setObjectName("varsetList")
        self.verticalLayout_2.addWidget(self.varsetList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btAdd = QtGui.QPushButton(AnswerEditWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btAdd.sizePolicy().hasHeightForWidth())
        self.btAdd.setSizePolicy(sizePolicy)
        self.btAdd.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btAdd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icons/add_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAdd.setIcon(icon)
        self.btAdd.setObjectName("btAdd")
        self.horizontalLayout.addWidget(self.btAdd)
        self.btDel = QtGui.QPushButton(AnswerEditWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDel.sizePolicy().hasHeightForWidth())
        self.btDel.setSizePolicy(sizePolicy)
        self.btDel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btDel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../icons/remove_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btDel.setIcon(icon1)
        self.btDel.setObjectName("btDel")
        self.horizontalLayout.addWidget(self.btDel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.layVariants = QtGui.QVBoxLayout()
        self.layVariants.setObjectName("layVariants")
        self.label_2 = QtGui.QLabel(AnswerEditWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.layVariants.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.layVariants)
        self.layRoles = QtGui.QVBoxLayout()
        self.layRoles.setObjectName("layRoles")
        self.label_3 = QtGui.QLabel(AnswerEditWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.layRoles.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.layRoles)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(AnswerEditWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinNumVariants = QtGui.QSpinBox(AnswerEditWidget)
        self.spinNumVariants.setMinimum(2)
        self.spinNumVariants.setMaximum(50)
        self.spinNumVariants.setObjectName("spinNumVariants")
        self.horizontalLayout_2.addWidget(self.spinNumVariants)
        self.btOk = QtGui.QPushButton(AnswerEditWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../icons/button_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btOk.setIcon(icon2)
        self.btOk.setObjectName("btOk")
        self.horizontalLayout_2.addWidget(self.btOk)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(AnswerEditWidget)
        QtCore.QMetaObject.connectSlotsByName(AnswerEditWidget)

    def retranslateUi(self, AnswerEditWidget):
        AnswerEditWidget.setWindowTitle(QtGui.QApplication.translate("AnswerEditWidget", "Answer editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AnswerEditWidget", "Введите варианты ответов:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AnswerEditWidget", "Укажите \"роль\" ответа:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AnswerEditWidget", "Число вариантов ответов:", None, QtGui.QApplication.UnicodeUTF8))
        self.btOk.setText(QtGui.QApplication.translate("AnswerEditWidget", "Ок", None, QtGui.QApplication.UnicodeUTF8))

