# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teaport.ui'
#
# Created: Wed Aug 18 03:16:11 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 331)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabIntro = QtGui.QWidget()
        self.tabIntro.setObjectName("tabIntro")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabIntro)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.tabIntro)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.text_intro = QtGui.QTextEdit(self.tabIntro)
        self.text_intro.setObjectName("text_intro")
        self.verticalLayout_2.addWidget(self.text_intro)
        self.label_3 = QtGui.QLabel(self.tabIntro)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.text_instruction = QtGui.QTextEdit(self.tabIntro)
        self.text_instruction.setObjectName("text_instruction")
        self.verticalLayout_2.addWidget(self.text_instruction)
        self.tabWidget.addTab(self.tabIntro, "")
        self.tabQuestions = QtGui.QWidget()
        self.tabQuestions.setObjectName("tabQuestions")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabQuestions)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.tabQuestions)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.text_questions = QtGui.QTextEdit(self.tabQuestions)
        self.text_questions.setObjectName("text_questions")
        self.verticalLayout_3.addWidget(self.text_questions)
        self.tabWidget.addTab(self.tabQuestions, "")
        self.tabAnswers = QtGui.QWidget()
        self.tabAnswers.setObjectName("tabAnswers")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabAnswers)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget.addTab(self.tabAnswers, "")
        self.tabCalculate = QtGui.QWidget()
        self.tabCalculate.setObjectName("tabCalculate")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabCalculate)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget.addTab(self.tabCalculate, "")
        self.tabInterp = QtGui.QWidget()
        self.tabInterp.setObjectName("tabInterp")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabInterp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableInterp = QtGui.QTableWidget(self.tabInterp)
        self.tableInterp.setObjectName("tableInterp")
        self.tableInterp.setColumnCount(0)
        self.tableInterp.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableInterp)
        self.tabWidget.addTab(self.tabInterp, "")
        self.tabGraph = QtGui.QWidget()
        self.tabGraph.setObjectName("tabGraph")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabGraph)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget.addTab(self.tabGraph, "")
        self.tabHelp = QtGui.QWidget()
        self.tabHelp.setObjectName("tabHelp")
        self.tabWidget.addTab(self.tabHelp, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btOk = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/button_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btOk.setIcon(icon)
        self.btOk.setObjectName("btOk")
        self.horizontalLayout.addWidget(self.btOk)
        self.btCancel = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCancel.setIcon(icon1)
        self.btCancel.setObjectName("btCancel")
        self.horizontalLayout.addWidget(self.btCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setIcon(icon1)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Введите текст, отображаемый при запуске программы:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Введите инструкцию для испытуемого:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntro), QtGui.QApplication.translate("MainWindow", "Инструкция", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Введите вопросы теста.\n"
"Каждый вопрос должен располагаться на отдельной строчке.\n"
"Не оставляйте пустых строк.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabQuestions), QtGui.QApplication.translate("MainWindow", "Вопросы", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnswers), QtGui.QApplication.translate("MainWindow", "Ответы", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCalculate), QtGui.QApplication.translate("MainWindow", "Расчёт результатов", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInterp), QtGui.QApplication.translate("MainWindow", "Интерпретация", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraph), QtGui.QApplication.translate("MainWindow", "График", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), QtGui.QApplication.translate("MainWindow", "Помощь", None, QtGui.QApplication.UnicodeUTF8))
        self.btOk.setText(QtGui.QApplication.translate("MainWindow", "Готово", None, QtGui.QApplication.UnicodeUTF8))
        self.btCancel.setText(QtGui.QApplication.translate("MainWindow", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "Создать", None, QtGui.QApplication.UnicodeUTF8))
        self.action_2.setText(QtGui.QApplication.translate("MainWindow", "Открыть", None, QtGui.QApplication.UnicodeUTF8))
        self.action_4.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))

